name: Schedule g03
on:
  schedule:
    - cron: '40 16 * * *' 
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Create directory for the previous day
        run: |
          yesterday=$(date -d "yesterday" +'%Y_%m%d')
          mkdir -p "${yesterday}"

      - name: Install dependencies
        run: pip install pandas requests beautifulsoup4 pytz boto3
      
      - name: Run scraper
        run: python py/file-g03.py

      - name: Set Git Config
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"

      - name: Pull remote changes
        run: git pull origin main

      - name: Commit and push csv files
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit, skipping."
          else
            git commit -m "Update csv files - $(date +'%Y-%m-%d')"
            git push
          fi
        working-directory: ${{ github.workspace }}
